import javax.microedition.lcdui.Graphics;
/*
 * Auxiliar.java
 *
 * Created on 19 de noviembre de 2007, 21:55
 *
 * To change this template, choose Tools | Template Manager
 * and open the template in the editor.
 */

/**
 *
 * @author javier
 */
public  class Auxiliar {
    public int [] tipo;
    private String [] descripcion;
    private int [] indice;
    public final int numero_propiedades_puntos;
    public final int numero_iconos;
    
    /** Creates a new instance of Auxiliar */
    public Auxiliar() {
        numero_propiedades_puntos=277;
        numero_iconos=136;
        int contador=0;
        tipo = new int [numero_propiedades_puntos];
        descripcion=new String [numero_propiedades_puntos];
        indice=new int [numero_propiedades_puntos];
        contador++; tipo[contador] = 0x100; descripcion[contador] = "City (pop. over 8M)"; indice[contador] = 01;
        contador++; tipo[contador] = 0x200; descripcion[contador] = "City (pop. 4-8M)"; indice[contador] = 01;
        contador++; tipo[contador] = 0x300; descripcion[contador] = "City (pop. 2-4M)"; indice[contador] = 02;
        contador++; tipo[contador] = 0x400; descripcion[contador] = "City (pop. 1-2M)"; indice[contador] = 03;
        contador++; tipo[contador] = 0x500; descripcion[contador] = "City (pop. 0.5-1M)"; indice[contador] = 03;
        contador++; tipo[contador] = 0x600; descripcion[contador] = "City (pop. 200-500K)"; indice[contador] = 03;
        contador++; tipo[contador] = 0x700; descripcion[contador] = "City (pop. 100-200K)"; indice[contador] = 04;
        contador++; tipo[contador] = 0x800; descripcion[contador] = "City (pop. 50-100K)"; indice[contador] = 04;
        contador++; tipo[contador] = 0x900; descripcion[contador] = "City (pop. 20-50K)"; indice[contador] = 04;
        contador++; tipo[contador] = 0xA00; descripcion[contador] = "Town (pop. 10-20K)"; indice[contador] = 05;
        contador++; tipo[contador] = 0xB00; descripcion[contador] = "Town (pop. 4-10K)"; indice[contador] = 05;
        contador++; tipo[contador] = 0xC00; descripcion[contador] = "Town (pop. 2-4K)"; indice[contador] = 05;
        contador++; tipo[contador] = 0xD00; descripcion[contador] = "Town (pop. 1-2K)"; indice[contador] = 05;
        contador++; tipo[contador] = 0xE00; descripcion[contador] = "Town (pop. 0.5-1K)"; indice[contador] = 06;
        contador++; tipo[contador] = 0xF00; descripcion[contador] = "Town (pop. 200-500)"; indice[contador] = 06;
        contador++; tipo[contador] = 0x1000; descripcion[contador] = "Town (pop. 100-200)"; indice[contador] = 06;
        contador++; tipo[contador] = 0x1100; descripcion[contador] = "Town (pop. under 100)"; indice[contador] = 06;
        contador++; tipo[contador] = 0x1200; descripcion[contador] = "Marina with facilities"; indice[contador] = 07;
        contador++; tipo[contador] = 0x1300; descripcion[contador] = "Marine unknown"; indice[contador] = 00;
        contador++; tipo[contador] = 0x1400; descripcion[contador] = "Major country name (no point)"; indice[contador] = 8;
        contador++; tipo[contador] = 0x1500; descripcion[contador] = "Minor country name (no point)"; indice[contador] = 8;
        contador++; tipo[contador] = 0x1600; descripcion[contador] = "Navaid"; indice[contador] = 10;
        contador++; tipo[contador] = 0x1601; descripcion[contador] = "Forg horn"; indice[contador] = 11;
        contador++; tipo[contador] = 0x1602; descripcion[contador] = "Radio beacon"; indice[contador] = 12;
        contador++; tipo[contador] = 0x1603; descripcion[contador] = "Racon"; indice[contador] = 12;
        contador++; tipo[contador] = 0x1604; descripcion[contador] = "Daybeacon (red triangle)"; indice[contador] = 13;
        contador++; tipo[contador] = 0x1605; descripcion[contador] = "Daybeacon (green square)"; indice[contador] = 14;
        contador++; tipo[contador] = 0x1606; descripcion[contador] = "Unlit navaid (white diamond)"; indice[contador] = 15;
        contador++; tipo[contador] = 0x1607; descripcion[contador] = "Unlit navaid (white)"; indice[contador] = 16;
        contador++; tipo[contador] = 0x1608; descripcion[contador] = "Unlit navaid (red)"; indice[contador] = 17;
        contador++; tipo[contador] = 0x1609; descripcion[contador] = "Unlit navaid (green)"; indice[contador] = 18;
        contador++; tipo[contador] = 0x160A; descripcion[contador] = "Unlit navaid (black)"; indice[contador] = 19;
        contador++; tipo[contador] = 0x160B; descripcion[contador] = "Unlit navaid (yellow/amber)"; indice[contador] = 20;
        contador++; tipo[contador] = 0x160C; descripcion[contador] = "Unlit navaid (orange)"; indice[contador] = 21;
        contador++; tipo[contador] = 0x160D; descripcion[contador] = "Unlit navaid (multi-colored)"; indice[contador] = 22;
        contador++; tipo[contador] = 0x160E; descripcion[contador] = "Navaid"; indice[contador] = 10;
        contador++; tipo[contador] = 0x160F; descripcion[contador] = "Navaid (white)"; indice[contador] = 23;
        contador++; tipo[contador] = 0x1610; descripcion[contador] = "Navaid (red)"; indice[contador] = 24;
        contador++; tipo[contador] = 0x1611; descripcion[contador] = "Navaid (green)"; indice[contador] = 25;
        contador++; tipo[contador] = 0x1612; descripcion[contador] = "Navaid (yellow/amber)"; indice[contador] = 26;
        contador++; tipo[contador] = 0x1613; descripcion[contador] = "Navaid (orange)"; indice[contador] = 27;
        contador++; tipo[contador] = 0x1614; descripcion[contador] = "Navaid (violet)"; indice[contador] = 28;
        contador++; tipo[contador] = 0x1615; descripcion[contador] = "Navaid (blue)"; indice[contador] = 29;
        contador++; tipo[contador] = 0x1616; descripcion[contador] = "Navaid (multi-colored)"; indice[contador] = 30;
        contador++; tipo[contador] = 0x1C00; descripcion[contador] = "Obstruction"; indice[contador] = 31;
        contador++; tipo[contador] = 0x1C01; descripcion[contador] = "Wreck"; indice[contador] = 32;
        contador++; tipo[contador] = 0x1C02; descripcion[contador] = "Submerged wreck, dangerous"; indice[contador] = 33;
        contador++; tipo[contador] = 0x1C03; descripcion[contador] = "Submerged wreck, non-dangerous"; indice[contador] = 34;
        contador++; tipo[contador] = 0x1C04; descripcion[contador] = "Wreck, cleared by wire-drag"; indice[contador] = 35;
        contador++; tipo[contador] = 0x1C05; descripcion[contador] = "Obstruction, visible at high water"; indice[contador] = 04;
        contador++; tipo[contador] = 0x1C06; descripcion[contador] = "Obstruction, awash"; indice[contador] = 04;
        contador++; tipo[contador] = 0x1C07; descripcion[contador] = "Obstruction, submerged"; indice[contador] = 31;
        contador++; tipo[contador] = 0x1C08; descripcion[contador] = "Obstruction, cleared by wire-drag"; indice[contador] = 36;
        contador++; tipo[contador] = 0x1C09; descripcion[contador] = "Rock, awash"; indice[contador] = 37;
        contador++; tipo[contador] = 0x1C0A; descripcion[contador] = "Rock, submerged at low water"; indice[contador] = 38;
        contador++; tipo[contador] = 0x1C0B; descripcion[contador] = "Sounding"; indice[contador] = 39;
        contador++; tipo[contador] = 0x1D00; descripcion[contador] = "Tide"; indice[contador] = 40;
        contador++; tipo[contador] = 0x1D01; descripcion[contador] = "Tide prediction"; indice[contador] = 40;
        contador++; tipo[contador] = 0x1D02; descripcion[contador] = "Tide prediction"; indice[contador] = 40;
        contador++; tipo[contador] = 0x1E00; descripcion[contador] = "Region, medium (no point)"; indice[contador] = 8;
        contador++; tipo[contador] = 0x1F00; descripcion[contador] = "Region, medium (no point)"; indice[contador] = 8;
        contador++; tipo[contador] = 0x2000; descripcion[contador] = "Exit"; indice[contador] = 41;
        contador++; tipo[contador] = 0x2100; descripcion[contador] = "Exit, with facilities"; indice[contador] = 41;
        contador++; tipo[contador] = 0x210F; descripcion[contador] = "Exit, service"; indice[contador] = 41;
        contador++; tipo[contador] = 0x2200; descripcion[contador] = "Exit, restroom"; indice[contador] = 42;
        contador++; tipo[contador] = 0x2300; descripcion[contador] = "Exit, convenience store"; indice[contador] = 41;
        contador++; tipo[contador] = 0x2400; descripcion[contador] = "Exit, weigh station"; indice[contador] = 43;
        contador++; tipo[contador] = 0x2500; descripcion[contador] = "Exit, toll booth"; indice[contador] = 44;
        contador++; tipo[contador] = 0x2600; descripcion[contador] = "Exit, information"; indice[contador] = 94;
        contador++; tipo[contador] = 0x2700; descripcion[contador] = "Exit"; indice[contador] = 41;
        contador++; tipo[contador] = 0x2800; descripcion[contador] = "Region, small (no point)"; indice[contador] = 8;
        contador++; tipo[contador] = 0x2900; descripcion[contador] = "Region"; indice[contador] = 126;
        contador++; tipo[contador] = 0x2A00; descripcion[contador] = "Food & Drink"; indice[contador] = 45;
        contador++; tipo[contador] = 0x2A01; descripcion[contador] = "Food & Drink, American"; indice[contador] = 45;
        contador++; tipo[contador] = 0x2A02; descripcion[contador] = "Food & Drink, Asian"; indice[contador] = 45;
        contador++; tipo[contador] = 0x2A03; descripcion[contador] = "Food & Drink, Barbeque"; indice[contador] = 45;
        contador++; tipo[contador] = 0x2A04; descripcion[contador] = "Food & Drink, Chinese"; indice[contador] = 45;
        contador++; tipo[contador] = 0x2A05; descripcion[contador] = "Food & Drink, Deli/Bakery"; indice[contador] = 45;
        contador++; tipo[contador] = 0x2A06; descripcion[contador] = "Food & Drink, International"; indice[contador] = 45;
        contador++; tipo[contador] = 0x2A07; descripcion[contador] = "Food & Drink, Fast Food"; indice[contador] = 45;
        contador++; tipo[contador] = 0x2A08; descripcion[contador] = "Food & Drink, Italian"; indice[contador] = 45;
        contador++; tipo[contador] = 0x2A09; descripcion[contador] = "Food & Drink, Mexican"; indice[contador] = 45;
        contador++; tipo[contador] = 0x2A0A; descripcion[contador] = "Food & Drink, Pizza"; indice[contador] = 45;
        contador++; tipo[contador] = 0x2A0B; descripcion[contador] = "Food & Drink, Seafood"; indice[contador] = 45;
        contador++; tipo[contador] = 0x2A0C; descripcion[contador] = "Food & Drink, Steak/Grill"; indice[contador] = 45;
        contador++; tipo[contador] = 0x2A0D; descripcion[contador] = "Food & Drink, Bagel/Doughnut"; indice[contador] = 45;
        contador++; tipo[contador] = 0x2A0E; descripcion[contador] = "Food & Drink, Cafe/Diner"; indice[contador] = 45;
        contador++; tipo[contador] = 0x2A0F; descripcion[contador] = "Food & Drink, French"; indice[contador] = 45;
        contador++; tipo[contador] = 0x2A10; descripcion[contador] = "Food & Drink, German"; indice[contador] = 45;
        contador++; tipo[contador] = 0x2A11; descripcion[contador] = "Food & Drink, British Isles"; indice[contador] = 45;
        contador++; tipo[contador] = 0x2A12; descripcion[contador] = "Special food products"; indice[contador] = 45;
        contador++; tipo[contador] = 0x2B00; descripcion[contador] = "Lodging"; indice[contador] = 46;
        contador++; tipo[contador] = 0x2B01; descripcion[contador] = "Lodging, Hotel/Motel"; indice[contador] = 46;
        contador++; tipo[contador] = 0x2B02; descripcion[contador] = "Lodging, Bed & Breakfast/Inn"; indice[contador] = 46;
        contador++; tipo[contador] = 0x2B03; descripcion[contador] = "Lodging, Campground/RV Park"; indice[contador] = 47;
        contador++; tipo[contador] = 0x2B04; descripcion[contador] = "Lodging, Resort"; indice[contador] = 46;
        contador++; tipo[contador] = 0x2C00; descripcion[contador] = "Attraction"; indice[contador] = 48;
        contador++; tipo[contador] = 0x2C01; descripcion[contador] = "Recreation, Amusement/Theme Park"; indice[contador] = 49;
        contador++; tipo[contador] = 0x2C02; descripcion[contador] = "Attraction, Museum/Historical"; indice[contador] = 50;
        contador++; tipo[contador] = 0x2C03; descripcion[contador] = "Community, Library"; indice[contador] = 51;
        contador++; tipo[contador] = 0x2C04; descripcion[contador] = "Attraction, Landmark"; indice[contador] = 52;
        contador++; tipo[contador] = 0x2C05; descripcion[contador] = "Community, School"; indice[contador] = 53;
        contador++; tipo[contador] = 0x2C06; descripcion[contador] = "Attraction, Park/Garden"; indice[contador] = 54;
        contador++; tipo[contador] = 0x2C07; descripcion[contador] = "Attraction, Zoo/Aquarium"; indice[contador] = 55;
        contador++; tipo[contador] = 0x2C08; descripcion[contador] = "Recreation, Arena/Track"; indice[contador] = 56;
        contador++; tipo[contador] = 0x2C09; descripcion[contador] = "Attraction, Hall/Auditorium"; indice[contador] = 48;
        contador++; tipo[contador] = 0x2C0A; descripcion[contador] = "Attraction, Winery"; indice[contador] = 57;
        contador++; tipo[contador] = 0x2C0B; descripcion[contador] = "Community, Place of Worship"; indice[contador] = 58;
        contador++; tipo[contador] = 0x2C0C; descripcion[contador] = "Attraction, Hot Spring"; indice[contador] = 01;
        contador++; tipo[contador] = 0x2D00; descripcion[contador] = "Entertainment"; indice[contador] = 59;
        contador++; tipo[contador] = 0x2D01; descripcion[contador] = "Entertainment, Live Theater"; indice[contador] = 60;
        contador++; tipo[contador] = 0x2D02; descripcion[contador] = "Entertainment, Bar/Nightclub"; indice[contador] = 61;
        contador++; tipo[contador] = 0x2D03; descripcion[contador] = "Entertainment, Cinema"; indice[contador] = 135;
        contador++; tipo[contador] = 0x2D04; descripcion[contador] = "Entertainment, Casino"; indice[contador] = 62;
        contador++; tipo[contador] = 0x2D05; descripcion[contador] = "Entertainment, Golf Course"; indice[contador] = 63;
        contador++; tipo[contador] = 0x2D06; descripcion[contador] = "Recreation, Skiing Center/Resort"; indice[contador] = 64;
        contador++; tipo[contador] = 0x2D07; descripcion[contador] = "Entertainment, Bowling"; indice[contador] = 65;
        contador++; tipo[contador] = 0x2D08; descripcion[contador] = "Entertainment, Ice Skating"; indice[contador] = 66;
        contador++; tipo[contador] = 0x2D09; descripcion[contador] = "Entertainment, Swimming Pool"; indice[contador] = 67;
        contador++; tipo[contador] = 0x2D0A; descripcion[contador] = "Entertainment, Sports/Fitness Center"; indice[contador] = 56;
        contador++; tipo[contador] = 0x2D0B; descripcion[contador] = "Entertainment, Sport Airport"; indice[contador] = 68;
        contador++; tipo[contador] = 0x2E00; descripcion[contador] = "Shopping"; indice[contador] = 69;
        contador++; tipo[contador] = 0x2E01; descripcion[contador] = "Shopping, Department Store"; indice[contador] = 70;
        contador++; tipo[contador] = 0x2E02; descripcion[contador] = "Shopping, Grocery Store"; indice[contador] = 69;
        contador++; tipo[contador] = 0x2E03; descripcion[contador] = "Shopping, General Merchandise"; indice[contador] = 69;
        contador++; tipo[contador] = 0x2E04; descripcion[contador] = "Shopping Center"; indice[contador] = 69;
        contador++; tipo[contador] = 0x2E05; descripcion[contador] = "Shopping, Pharmacy"; indice[contador] = 71;
        contador++; tipo[contador] = 0x2E06; descripcion[contador] = "Shopping, Convenience Store"; indice[contador] = 69;
        contador++; tipo[contador] = 0x2E07; descripcion[contador] = "Shopping, Apparel"; indice[contador] = 69;
        contador++; tipo[contador] = 0x2E08; descripcion[contador] = "Shopping, Home and Garden"; indice[contador] = 69;
        contador++; tipo[contador] = 0x2E09; descripcion[contador] = "Shopping, Home Furnishings"; indice[contador] = 69;
        contador++; tipo[contador] = 0x2E0A; descripcion[contador] = "Shopping, Specialty Retail"; indice[contador] = 69;
        contador++; tipo[contador] = 0x2E0B; descripcion[contador] = "Shopping, Computer/Software"; indice[contador] = 69;
        contador++; tipo[contador] = 0x2E0C; descripcion[contador] = "Shopping, Other"; indice[contador] = 69;
        contador++; tipo[contador] = 0x2F00; descripcion[contador] = "Service"; indice[contador] = 72;
        contador++; tipo[contador] = 0x2F01; descripcion[contador] = "Service, Auto Fuel"; indice[contador] = 73;
        contador++; tipo[contador] = 0x2F02; descripcion[contador] = "Service, Auto Rental"; indice[contador] = 74;
        contador++; tipo[contador] = 0x2F03; descripcion[contador] = "Service, Auto Repair"; indice[contador] = 75;
        contador++; tipo[contador] = 0x2F04; descripcion[contador] = "Service, Air Transportation"; indice[contador] = 68;
        contador++; tipo[contador] = 0x2F05; descripcion[contador] = "Service, Post Office"; indice[contador] = 76;
        contador++; tipo[contador] = 0x2F06; descripcion[contador] = "Service, Bank/ATM"; indice[contador] = 77;
        contador++; tipo[contador] = 0x2F07; descripcion[contador] = "Service, Dealer/Auto Parts"; indice[contador] = 78;
        contador++; tipo[contador] = 0x2F08; descripcion[contador] = "Service, Ground Transportation"; indice[contador] = 79;
        contador++; tipo[contador] = 0x2F09; descripcion[contador] = "Service, Marina/Boat Repair"; indice[contador] = 07;
        contador++; tipo[contador] = 0x2F0A; descripcion[contador] = "Service, Wrecker"; indice[contador] = 75;
        contador++; tipo[contador] = 0x2F0B; descripcion[contador] = "Service, Parking"; indice[contador] = 80;
        contador++; tipo[contador] = 0x2F0C; descripcion[contador] = "Service, Rest Area/Information"; indice[contador] = 42;
        contador++; tipo[contador] = 0x2F0D; descripcion[contador] = "Service, Auto Club"; indice[contador] = 81;
        contador++; tipo[contador] = 0x2F0E; descripcion[contador] = "Service, Car Wash"; indice[contador] = 82;
        contador++; tipo[contador] = 0x2F0F; descripcion[contador] = "Service, Garmin Dealer"; indice[contador] = 69;
        contador++; tipo[contador] = 0x2F10; descripcion[contador] = "Service, Personal"; indice[contador] = 72;
        contador++; tipo[contador] = 0x2F11; descripcion[contador] = "Service, Business"; indice[contador] = 72;
        contador++; tipo[contador] = 0x2F12; descripcion[contador] = "Service, Communication"; indice[contador] = 83;
        contador++; tipo[contador] = 0x2F13; descripcion[contador] = "Service, Repair"; indice[contador] = 72;
        contador++; tipo[contador] = 0x2F14; descripcion[contador] = "Service, Social"; indice[contador] = 72;
        contador++; tipo[contador] = 0x2F15; descripcion[contador] = "Service, Public Utility"; indice[contador] = 72;
        contador++; tipo[contador] = 0x2F16; descripcion[contador] = "Truck stop"; indice[contador] = 84;
        contador++; tipo[contador] = 0x2F17; descripcion[contador] = "Transit service"; indice[contador] = 72;
        contador++; tipo[contador] = 0x3000; descripcion[contador] = "Emergency/Government"; indice[contador] = 85;
        contador++; tipo[contador] = 0x3001; descripcion[contador] = "Community, Police Station"; indice[contador] = 86;
        contador++; tipo[contador] = 0x3002; descripcion[contador] = "Hospital"; indice[contador] = 87;
        contador++; tipo[contador] = 0x3003; descripcion[contador] = "Community, City Hall"; indice[contador] = 85;
        contador++; tipo[contador] = 0x3004; descripcion[contador] = "Community, Court House"; indice[contador] = 88;
        contador++; tipo[contador] = 0x3005; descripcion[contador] = "Community, Community Center"; indice[contador] = 85;
        contador++; tipo[contador] = 0x3006; descripcion[contador] = "Community, Border Crossing"; indice[contador] = 85;
        contador++; tipo[contador] = 0x3007; descripcion[contador] = "Government Office"; indice[contador] = 85;
        contador++; tipo[contador] = 0x3008; descripcion[contador] = "Fire Department"; indice[contador] = 89;
        contador++; tipo[contador] = 0x4000; descripcion[contador] = "Golf"; indice[contador] = 63;
        contador++; tipo[contador] = 0x4100; descripcion[contador] = "Fishing"; indice[contador] = 90;
        contador++; tipo[contador] = 0x4200; descripcion[contador] = "Wreck"; indice[contador] = 91;
        contador++; tipo[contador] = 0x4300; descripcion[contador] = "Marina"; indice[contador] = 07;
        contador++; tipo[contador] = 0x4400; descripcion[contador] = "Gas Station"; indice[contador] = 73;
        contador++; tipo[contador] = 0x4500; descripcion[contador] = "Food & Drink"; indice[contador] = 45;
        contador++; tipo[contador] = 0x4600; descripcion[contador] = "Bar"; indice[contador] = 61;
        contador++; tipo[contador] = 0x4700; descripcion[contador] = "Boat Ramp"; indice[contador] = 92;
        contador++; tipo[contador] = 0x4800; descripcion[contador] = "Camping"; indice[contador] = 47;
        contador++; tipo[contador] = 0x4900; descripcion[contador] = "Park"; indice[contador] = 54;
        contador++; tipo[contador] = 0x4A00; descripcion[contador] = "Picnic Area"; indice[contador] = 93;
        contador++; tipo[contador] = 0x4B00; descripcion[contador] = "First Aid"; indice[contador] = 87;
        contador++; tipo[contador] = 0x4C00; descripcion[contador] = "Information"; indice[contador] = 94;
        contador++; tipo[contador] = 0x4D00; descripcion[contador] = "Parking"; indice[contador] = 80;
        contador++; tipo[contador] = 0x4E00; descripcion[contador] = "Restroom"; indice[contador] = 42;
        contador++; tipo[contador] = 0x4F00; descripcion[contador] = "Shower"; indice[contador] = 95;
        contador++; tipo[contador] = 0x5000; descripcion[contador] = "Drinking Water"; indice[contador] = 96;
        contador++; tipo[contador] = 0x5100; descripcion[contador] = "Telephone"; indice[contador] = 83;
        contador++; tipo[contador] = 0x5200; descripcion[contador] = "Scenic Area"; indice[contador] = 52;
        contador++; tipo[contador] = 0x5300; descripcion[contador] = "Skiing"; indice[contador] = 64;
        contador++; tipo[contador] = 0x5400; descripcion[contador] = "Swimming"; indice[contador] = 67;
        contador++; tipo[contador] = 0x5500; descripcion[contador] = "Dam"; indice[contador] = 97;
        contador++; tipo[contador] = 0x5600; descripcion[contador] = "Controlled area"; indice[contador] = 98;
        contador++; tipo[contador] = 0x5700; descripcion[contador] = "Danger"; indice[contador] = 99;
        contador++; tipo[contador] = 0x5800; descripcion[contador] = "Restricted Area"; indice[contador] = 100;
        contador++; tipo[contador] = 0x5900; descripcion[contador] = "Airport"; indice[contador] = 68;
        contador++; tipo[contador] = 0x5901; descripcion[contador] = "Airport, Large"; indice[contador] = 101;
        contador++; tipo[contador] = 0x5902; descripcion[contador] = "Airport, Medium"; indice[contador] = 68;
        contador++; tipo[contador] = 0x5903; descripcion[contador] = "Airport, Small"; indice[contador] = 68;
        contador++; tipo[contador] = 0x5904; descripcion[contador] = "Heliport"; indice[contador] = 102;
        contador++; tipo[contador] = 0x5905; descripcion[contador] = "Airport"; indice[contador] = 68;
        contador++; tipo[contador] = 0x5A00; descripcion[contador] = "Mile marker"; indice[contador] = 103;
        contador++; tipo[contador] = 0x5B00; descripcion[contador] = "Bell"; indice[contador] = 04;
        contador++; tipo[contador] = 0x5C00; descripcion[contador] = "Diving area"; indice[contador] = 105;
        contador++; tipo[contador] = 0x5D00; descripcion[contador] = "Daymark, green square"; indice[contador] = 14;
        contador++; tipo[contador] = 0x5E00; descripcion[contador] = "Daymark, red triangle"; indice[contador] = 13;
        contador++; tipo[contador] = 0x6000; descripcion[contador] = "Horn"; indice[contador] = 11;
        contador++; tipo[contador] = 0x6100; descripcion[contador] = "House"; indice[contador] = 106;
        contador++; tipo[contador] = 0x6200; descripcion[contador] = "Depth"; indice[contador] = 8;
        contador++; tipo[contador] = 0x6300; descripcion[contador] = "Elevation"; indice[contador] = 8;
        contador++; tipo[contador] = 0x6400; descripcion[contador] = "Man-made Feature"; indice[contador] = 107;
        contador++; tipo[contador] = 0x6401; descripcion[contador] = "Bridge"; indice[contador] = 108;
        contador++; tipo[contador] = 0x6402; descripcion[contador] = "Building"; indice[contador] = 106;
        contador++; tipo[contador] = 0x6403; descripcion[contador] = "Cemetary"; indice[contador] = 109;
        contador++; tipo[contador] = 0x6404; descripcion[contador] = "Church"; indice[contador] = 58;
        contador++; tipo[contador] = 0x6405; descripcion[contador] = "Civil Building"; indice[contador] = 85;
        contador++; tipo[contador] = 0x6406; descripcion[contador] = "Crossing"; indice[contador] = 110;
        contador++; tipo[contador] = 0x6407; descripcion[contador] = "Dam"; indice[contador] = 97;
        contador++; tipo[contador] = 0x6408; descripcion[contador] = "Hospital"; indice[contador] = 87;
        contador++; tipo[contador] = 0x6409; descripcion[contador] = "Levee"; indice[contador] = 97;
        contador++; tipo[contador] = 0x640A; descripcion[contador] = "Locale"; indice[contador] = 103;
        contador++; tipo[contador] = 0x640B; descripcion[contador] = "Military"; indice[contador] = 111;
        contador++; tipo[contador] = 0x640C; descripcion[contador] = "Mine"; indice[contador] = 112;
        contador++; tipo[contador] = 0x640D; descripcion[contador] = "Oil Field"; indice[contador] = 113;
        contador++; tipo[contador] = 0x640E; descripcion[contador] = "Park"; indice[contador] = 54;
        contador++; tipo[contador] = 0x640F; descripcion[contador] = "Post Office"; indice[contador] = 76;
        contador++; tipo[contador] = 0x6410; descripcion[contador] = "School"; indice[contador] = 53;
        contador++; tipo[contador] = 0x6411; descripcion[contador] = "Tower"; indice[contador] = 114;
        contador++; tipo[contador] = 0x6412; descripcion[contador] = "Trail"; indice[contador] = 115;
        contador++; tipo[contador] = 0x6413; descripcion[contador] = "Tunnel"; indice[contador] = 116;
        contador++; tipo[contador] = 0x6414; descripcion[contador] = "Well"; indice[contador] = 96;
        contador++; tipo[contador] = 0x6415; descripcion[contador] = "Ghost Town"; indice[contador] = 117;
        contador++; tipo[contador] = 0x6416; descripcion[contador] = "Subdivision"; indice[contador] = 117;
        contador++; tipo[contador] = 0x6500; descripcion[contador] = "Water Feature"; indice[contador] = 40;
        contador++; tipo[contador] = 0x6501; descripcion[contador] = "Arroyo"; indice[contador] = 118;
        contador++; tipo[contador] = 0x6502; descripcion[contador] = "Sand Bar"; indice[contador] = 40;
        contador++; tipo[contador] = 0x6503; descripcion[contador] = "Bay"; indice[contador] = 40;
        contador++; tipo[contador] = 0x6504; descripcion[contador] = "Bend"; indice[contador] = 40;
        contador++; tipo[contador] = 0x6505; descripcion[contador] = "Canal"; indice[contador] = 40;
        contador++; tipo[contador] = 0x6506; descripcion[contador] = "Channel"; indice[contador] = 40;
        contador++; tipo[contador] = 0x6507; descripcion[contador] = "Cove"; indice[contador] = 40;
        contador++; tipo[contador] = 0x6508; descripcion[contador] = "Falls"; indice[contador] = 119;
        contador++; tipo[contador] = 0x6509; descripcion[contador] = "Geyser"; indice[contador] = 120;
        contador++; tipo[contador] = 0x650A; descripcion[contador] = "Glacier"; indice[contador] = 40;
        contador++; tipo[contador] = 0x650B; descripcion[contador] = "Harbor"; indice[contador] = 40;
        contador++; tipo[contador] = 0x650C; descripcion[contador] = "Island"; indice[contador] = 121;
        contador++; tipo[contador] = 0x650D; descripcion[contador] = "Lake"; indice[contador] = 122;
        contador++; tipo[contador] = 0x650E; descripcion[contador] = "Rapids"; indice[contador] = 119;
        contador++; tipo[contador] = 0x650F; descripcion[contador] = "Resevoir"; indice[contador] = 122;
        contador++; tipo[contador] = 0x6510; descripcion[contador] = "Sea"; indice[contador] = 122;
        contador++; tipo[contador] = 0x6511; descripcion[contador] = "Spring"; indice[contador] = 123;
        contador++; tipo[contador] = 0x6512; descripcion[contador] = "Stream"; indice[contador] = 124;
        contador++; tipo[contador] = 0x6513; descripcion[contador] = "Swamp"; indice[contador] = 125;
        contador++; tipo[contador] = 0x6600; descripcion[contador] = "Land Feature"; indice[contador] = 126;
        contador++; tipo[contador] = 0x6601; descripcion[contador] = "Arch"; indice[contador] = 127;
        contador++; tipo[contador] = 0x6602; descripcion[contador] = "Area"; indice[contador] = 126;
        contador++; tipo[contador] = 0x6603; descripcion[contador] = "Basin"; indice[contador] = 122;
        contador++; tipo[contador] = 0x6604; descripcion[contador] = "Beach"; indice[contador] = 126;
        contador++; tipo[contador] = 0x6605; descripcion[contador] = "Bench"; indice[contador] = 126;
        contador++; tipo[contador] = 0x6606; descripcion[contador] = "Cape"; indice[contador] = 126;
        contador++; tipo[contador] = 0x6607; descripcion[contador] = "Cliff"; indice[contador] = 128;
        contador++; tipo[contador] = 0x6608; descripcion[contador] = "Crater"; indice[contador] = 129;
        contador++; tipo[contador] = 0x6609; descripcion[contador] = "Flat"; indice[contador] = 126;
        contador++; tipo[contador] = 0x660A; descripcion[contador] = "Forest"; indice[contador] = 130;
        contador++; tipo[contador] = 0x660B; descripcion[contador] = "Gap"; indice[contador] = 126;
        contador++; tipo[contador] = 0x660C; descripcion[contador] = "Gut"; indice[contador] = 126;
        contador++; tipo[contador] = 0x660D; descripcion[contador] = "Isthmus"; indice[contador] = 126;
        contador++; tipo[contador] = 0x660E; descripcion[contador] = "Lava"; indice[contador] = 131;
        contador++; tipo[contador] = 0x660F; descripcion[contador] = "Pillar"; indice[contador] = 132;
        contador++; tipo[contador] = 0x6610; descripcion[contador] = "Plain"; indice[contador] = 126;
        contador++; tipo[contador] = 0x6611; descripcion[contador] = "Range"; indice[contador] = 126;
        contador++; tipo[contador] = 0x6612; descripcion[contador] = "Reserve"; indice[contador] = 126;
        contador++; tipo[contador] = 0x6613; descripcion[contador] = "Ridge"; indice[contador] = 133;
        contador++; tipo[contador] = 0x6614; descripcion[contador] = "Rock"; indice[contador] = 133;
        contador++; tipo[contador] = 0x6615; descripcion[contador] = "Slope"; indice[contador] = 126;
        contador++; tipo[contador] = 0x6616; descripcion[contador] = "Summit"; indice[contador] = 134;
        contador++; tipo[contador] = 0x6617; descripcion[contador] = "Valley"; indice[contador] = 126;
        contador++; tipo[contador] = 0x6618; descripcion[contador] = "Woods"; indice[contador] = 130;
        contador++; tipo[contador] = 0xffff; descripcion[contador] = "Unknown"; indice[contador] = 6;
        
    }
    public Tipo_Propiedades_Punto leer_propiedades_punto(int tipo) {
        //busca y devuelve las propiedades asociadas a un tipo de punto
        int contador;
        for (contador=indice.length-1;contador>0;contador--) {
            if (this.tipo[contador]==tipo) break;
        }
        if (contador>0) { //tipo encontrado
            return new Tipo_Propiedades_Punto(this.tipo[contador],descripcion[contador],indice[contador]);
        } else { //tipo no encontrado. si es del tipo xx00 devuelve el tipo desconocido
            if (tipo%256==0) {
                return new Tipo_Propiedades_Punto(this.tipo[this.tipo.length-1],descripcion[this.descripcion.length-1],indice[this.indice.length-1]);
            } else { //si es tel tipo xxyy, devuelve el tipo de su jefe de categoría, el xx00
                return leer_propiedades_punto(tipo&0xff00);
            }
        }
    }
}
